public with sharing class SATConstants {
    public static final Set<String> standardObjs = new Set<String>{
        'Account',
        'Contact',
        'Campaign',
        'CampaignMember',
        'Lead',
        'Opportunity',
        'OpportunityTeam',
        'OpportunityLineItem',
        'Product2',
        'AccountTeam',
        'OpportunityContactRole',
        'Case',
        'Contract',
        'Event',
        'Task',
        'Pricebook',
        'PricebookEntry',
        'User'
    };

    public static final Set<String> pkgNameSpaces = new Set<String>{
        'vh',
        'sbqq',
        'sbaa',
        'pse',
        'pw_ccpro',
        'fcrm',
        'mkto2',
        'leandata'
    };
}
